on: push
name: CI
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install
        uses: CultureHQ/actions-yarn@master
        with:
          args: install
      - name: Lint
        uses: CultureHQ/actions-yarn@master
        with:
          args: lint
      - name: Type-Check
        uses: CultureHQ/actions-yarn@master
        with:
          args: type-check
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install
        uses: CultureHQ/actions-yarn@master
        with:
          args: install
      - name: Test
        uses: CultureHQ/actions-yarn@master
        with:
          args: test
